apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j5ht84ljt-dotnet-basic
  janus-idp.io/tekton: j5ht84ljt-dotnet-basic
  backstage.io/kubernetes-id: j5ht84ljt-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5ht84ljt-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
